name: Check new PHP releases.

on:
  schedule:
    - cron: "* 3 15 * *"

permissions:
  issues: write

jobs:
  notify_new_releases:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Check the new php releases.
        uses: sxbrsky/notify-php-release-action@v1.1.0
        with:
          repo-token: ${{ github.token }}
          repo: docker-php-fpm
          owner: sxbrsky
          localfile: .releases
